---
version: '3.7'
services:
  api:
    build:
      context: '.'
    ports:
      - target: 80
        published: 8081
        protocol: 'tcp'
        mode: 'host'
    volumes:
      - type: 'bind'
        source: '../api'
        target: '/var/www/html'
        read_only: true
  www:
    build:
      context: '.'
    ports:
      - target: 80
        published: 8080
        protocol: 'tcp'
        mode: 'host'
    volumes:
      - type: 'bind'
        source: '../www'
        target: '/var/www/html'
        read_only: true
...
