name: Deploy next Website to Development
on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: next

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NEXT_DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEXT_DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy
        run: npm run deploy:next
