name: Deploy to Staging
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to StableHost
        uses: ./.github/actions/deploy-stablehost
        with:
          environment: staging
          private_key: ${{ secrets.STABLEHOST_DEPLOY_SSH_KEY }}
